### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by rgrandi** [elevati/wp-api-multiple-posttype#1]
Hi there,
Getting a Error 500 (internal server error) when trying to make a GET request with your plugin.

I can see the route when I query `http://example.com/wp-json/wp/v2`, however when querying `http://example.com/wp-json/wp/v2/multiple-post-type?related_industry=transport` where Related Industry is a Taxonomy and the term is Transport, I get an error.

I've also tried both of your example strings, to test slug and search, and the same error occurs.

Any thoughts? Are there additional steps I must make to make this work?

Thanks,
R

**Comment by rgrandi** [comment]
Further to my last comment, I did a bit of debugging with axios and found that you need to pass in post types to the query such as:

`http://example.com/wp-json/wp/v2/multiple-post-type?type[]=question&type[]=post&related_industry=transport`

Hope this helps other users, as this doesn't seem to be in the documentation.

**Comment by salil-elevati** [comment]
Thanks for pointing out that, we have update the documentation.
