### ISSUE TITLE
Adding to packagist

### ISSUE THREAD

**Issue by stevep** [elevati/wp-api-multiple-posttype#10]
Can't wait to try this plugin. Just ran into an issue and found this library via https://github.com/WP-API/WP-API/issues/2567

I see you have a `composer.json` file. I went ahead and added it to [packagist.com](https://packagist.org/packages/elevati/wp-api-multiple-posttype) so I can require it in my theme's own `composer.json`. I thought I would let you know so you can take it over as well as set it up to auto update when you create new releases.

Thanks!

**Comment by salil-elevati** [comment]
As it is a wordpress plugin, and best way to use wordpress with composer is by using wordplate, we have added it to wpackagist.
https://wpackagist.org/search?q=wp-api-multiple-posttype&type=any&search=

**Comment by salil-elevati** [comment]
Hello Steve,
Please  give us maintainership access for https://packagist.org/packages/elevati/
and the package. Username salil-elevati.

**Comment by stevep** [comment]
@salil-elevati Done. Confirm then remove me. Thanks!

**Comment by salil-elevati** [comment]
Thanks.
