### ISSUE TITLE
Not working with 3 custom post types.

### ISSUE THREAD

**Issue by adamwright32** [elevati/wp-api-multiple-posttype#11]
Trying to return 3 custom post types

`http://localhost:8888/wp-json/wp/v2/multiple-post-type?&type[]=article&type[]=ebook&type[]=quickviews`

it only returns the first two.

**Comment by adamwright32** [comment]
any update on this?

**Comment by salil-elevati** [comment]
Hello,

- Can you try adding few more types. 
- Can you mention if it is the last in the order which does not show up or it is a particular post type.
These two tests will help to know the exact issue.

Thanks.

**Comment by MaximeCulea** [comment]
Hi there, 

On a project with multiple post types, it worked like a charm : 
`http://jdg.beapi.space/wp-json/wp/v2/multiple-post-type?per_page=8&exclude[0]=170&categories[0]=2&categories[1]=6&type[0]=post&type[1]=critique&type[2]=dossier&type[3]=page&type[4]=test`

So maybe a wrong implementation of the route's params ? 🤔
